### ISSUE TITLE
row[13] KeyError in extractCasesInfo Function in run.py

### ISSUE THREAD

**Issue by LichiY** [UT-SE-Research/ODRepair#3]
The extractCasesInfo function in run.py throws an error because it attempts to access row[13] in the following line:

case['field_fqn'] = row[13]

However, the provided CSV data does not include a 14th column (index 13).

**Comment by ChopinLi-cp** [comment]
Hi,

Thank you so much for reaching out!

I think the run.py accepts the csv generated from the first step. I think there maybe some exceptions at the first step. The 14th column should be the polluted static field. If in the generated file (output/result.csv), the column 14 is empty, it means either the first step has some errors or simply there are no polluted static fields found.

**Comment by ChopinLi-cp** [comment]
Oh, I think it can also be that you did not successfully install idflakies and testrunner. Maybe you can try to enter repos/ and `mvn install` them again. If you have any exceptions thrown during the first step (debugging phase), you can also share here.

**Comment by LichiY** [comment]
Hi,

Thank you for your prompt response and clarification!

I have double-checked the setup, and both the idflakies and testrunner repositories were successfully built with mvn install without any errors. When I ran` ./runAll.sh ./data/test.csv `， the execution proceeded up to the debugging phase, but an IndexError was encountered in the extractCasesInfo function due to accessing row[13] (static field) which does not exist in the generated CSV file.

Here’s the error message encountered during the execution of run.py:

```
Traceback (most recent call last):
  File "/home/lizhyu/libspace/flaky_repair_baselines/ODRepair/experiments/run.py", line 834, in <module>
    runExp()
  File "/home/lizhyu/libspace/flaky_repair_baselines/ODRepair/experiments/run.py", line 769, in runExp
    all_cases = extractCasesInfo(EXP_CSV)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lizhyu/libspace/flaky_repair_baselines/ODRepair/experiments/run.py", line 111, in extractCasesInfo
    case['field_fqn'] = row[13] # static field
                        ~~~^^^^
IndexError: list index out of range
```

The output directory (output/result.csv) only contains the following columns, as shown in the attached screenshot:

![image](https://github.com/user-attachments/assets/f78e5869-422e-4c24-bf3d-a62164bc8c1c)

There are no additional columns in the generated CSV file, and Column 14 (row[13]) is absent.

Thank you for your support!

**Comment by LichiY** [comment]
Thanks for your help, have found the problem is the path to the local maven repository configured in the individual scripts.

This is the case at the moment, thanks for the reply
![image](https://github.com/user-attachments/assets/a277fe6e-bdde-47d8-92d0-1b12a829b3db)

**Comment by LichiY** [comment]
Thanks for your reply

**Comment by ChopinLi-cp** [comment]
Sure, I think you can just insert the whole patch at the line 12 (right before `SerializeWriter writer = new SerializeWriter();`) in the test_max_buf function. And you don't need to change the original remaining test method bodies I assume.

**Comment by LichiY** [comment]
Thank you for your response and all the clarifications so far!

I have a question regarding the number of patches generated. In the `ODRepair/experiments/data/patches` directory, I only see 59 patches, whereas the paper mentions that there are 141 patches. Could you help clarify why there is such a discrepancy?

**Comment by ChopinLi-cp** [comment]
Sure, I think some patch matches for multiple tests. If the fields or polluters are the same in `data/results.csv`, the patches are also the same and we just put one in the repository.
